// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHes3vnJo6lnVWRTu26VsSOIQXk11TxU',
    appId: '1:698972634102:web:7c27381cef1a7ba3d465d7',
    messagingSenderId: '698972634102',
    projectId: 'mis-recepti',
    authDomain: 'mis-recepti.firebaseapp.com',
    storageBucket: 'mis-recepti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJxNzlLyCyeqZw6vTEYEM7fkIn931pRCU',
    appId: '1:698972634102:android:b5d53035bd589fded465d7',
    messagingSenderId: '698972634102',
    projectId: 'mis-recepti',
    storageBucket: 'mis-recepti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbaIC58XlXIP3n3zFlcKH20dTkSgm_st4',
    appId: '1:698972634102:ios:b807c55e1e4d7c4cd465d7',
    messagingSenderId: '698972634102',
    projectId: 'mis-recepti',
    storageBucket: 'mis-recepti.firebasestorage.app',
    iosBundleId: 'com.example.receptiApp',
  );

}